### ISSUE TITLE
How to preprocess MultiWOZ2.1?

### ISSUE THREAD

**Issue by SkyAndCloud** [henryhungle/NADST#1]
Hi, you wrote "We use the MultiWOZ benchmark, includin both version 2.0 and 2.1. The data can be found in the folder data in the repo root folder." in Dataset section. However, there are no folder named "data". I have downloaded MultiWOZ2.1 dataset, but how to preprocess it?

**Comment by henryhungle** [comment]
I will update the pre-processing scripts very soon.

**Comment by henryhungle** [comment]
@SkyAndCloud  I updated the links to download the data in the readme file.

**Comment by SparkJiao** [comment]
Hi, are your pre-processing scripts the same as those of TRADE ?

**Comment by henryhungle** [comment]
@SparkJiao Yes the pre-processing scripts are the same as in TRADE. Additional modifications are code to delexicalize dialogue utterances.
