### ISSUE TITLE
How to get the training dataset

### ISSUE THREAD

**Issue by SihengLi99** [henryhungle/NADST#10]
Hello~

Thanks for this great work!
I have some trouble with how to get the training dataset. Could you please share it with me?

sihengli99.11.10@gmail.com

**Comment by henryhungle** [comment]
Hi @SihengLi99, are you not able to get the data from the Google Drive links mentioned in the Readme file? The data in the drive should be publicly accessible.

**Comment by SihengLi99** [comment]
Thank you!

I have got it. Thank you for your response with patients.

Best,
Siheng

(Henry) Hung Le ***@***.***> 于2021年7月19日周一 下午1:43写道：
