### ISSUE TITLE
I have some feedback after read your code

### ISSUE THREAD

**Issue by koliaok** [henryhungle/NADST#4]
I have some feedback after read your NADST code review

first, your NADST paper page 6, and 3.3 State Decoder

you explained like this "where Wgen ∈ R3d×1 and Zexp is the expanded vector of Z to match dimensions of Zds×fert." 

I think more explained Z_exp, don't enough explain it in paper

your real code : 
- generators.py 
- line 57: 
`context_vec = (encoded_context.unsqueeze(1).expand_as(expanded_pointer_attn) * expanded_pointer_attn).sum(2)`

I think, need to more explain above code from "expanded_pointer_attn variable" for multiply expanded encoding context vector  

How about that?

**Comment by henryhungle** [comment]
Hi @koliaok, sorry for the confusion. In the paper, we try to describe our models in a concise way as there is the page limit. The representation `encoded_context` is expanded by simply stacking by |Zdsxfert| times as we want the resulting stack to be compatible with the attention matrix `pointer_attn`. The stacked vector is used to obtain the weighted sum of dialogue context embedding.
https://github.com/henryhungle/NADST/blob/afdc1d1f7ecb855b03933e441c0b2fcefbc28feb/model/generators.py#L57
The weighted sum is then concatenated to the other 2 representations to obtain a 3xd dimensional representation.
https://github.com/henryhungle/NADST/blob/afdc1d1f7ecb855b03933e441c0b2fcefbc28feb/model/generators.py#L58
This code is not a major part of our idea anyway. It is mainly to address the OOV problem in DST generation using a traditional pointer network.

**Comment by koliaok** [comment]
Ok Thank you for response 

Have nicely Henry
