### ISSUE TITLE
How to decide the domains contained in each dialogue?

### ISSUE THREAD

**Issue by SparkJiao** [henryhungle/NADST#5]
In other words, how could I get the results showed in Table 7?
Currently, I use the domains with non-empty goals in each dialogue, which is annotated as "goal" in `data.json`. But the results are highly than yours.

Thanks for your help!

**Comment by henryhungle** [comment]
I used the labels of dialogue states rather than the dialogue goals as I found some sampled dialogue goals contain noisy annotations. If a dialogue contains a non-empty state value from a domain, then that domain is active.
